version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: junit-report
    versions:
    - "> 0.2.1"
  - dependency-name: reqwest
    versions:
    - 0.11.3
  - dependency-name: serde
    versions:
    - 1.0.123
  - dependency-name: serde_yaml
    versions:
    - 0.8.16
  - dependency-name: log
    versions:
    - 0.4.14
  - dependency-name: serde_derive
    versions:
    - 1.0.123
