[package]
name = "git-mirror"
version = "0.2.3"
authors = ["Pascal Bach <pascal.bach@nextrem.ch>"]

[features]
native-tls = [ "hyper-native-tls" ]

[dependencies]
clap = "2.24.2"
log = "0.3.8"
stderrlog = "0.2.2"
slug = "0.1.2"
threadpool = "1.3.2"
hyper = "0.10.12"
hyper-native-tls = { version = "0.2.4", optional = true }
hyper-rustls = "0.6.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.7.0"
